// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV6wVv08BaahQeX8eF2Nsyosx9ri_WNlE',
    appId: '1:435112606639:web:a8deffafa23c8afc7c8d5a',
    messagingSenderId: '435112606639',
    projectId: 'team-socket',
    authDomain: 'team-socket.firebaseapp.com',
    databaseURL: 'https://team-socket-default-rtdb.firebaseio.com',
    storageBucket: 'team-socket.firebasestorage.app',
    measurementId: 'G-865LZWJWV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Go8R7K9clZuqtFaWGwKlGVLTYTmwroQ',
    appId: '1:435112606639:android:665186e6737bc4de7c8d5a',
    messagingSenderId: '435112606639',
    projectId: 'team-socket',
    databaseURL: 'https://team-socket-default-rtdb.firebaseio.com',
    storageBucket: 'team-socket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjW6psoADptq3rQ-dD1jHnZjY1HUzHF24',
    appId: '1:435112606639:ios:e82d970e7e3e75007c8d5a',
    messagingSenderId: '435112606639',
    projectId: 'team-socket',
    databaseURL: 'https://team-socket-default-rtdb.firebaseio.com',
    storageBucket: 'team-socket.firebasestorage.app',
    iosBundleId: 'com.example.socket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjW6psoADptq3rQ-dD1jHnZjY1HUzHF24',
    appId: '1:435112606639:ios:e82d970e7e3e75007c8d5a',
    messagingSenderId: '435112606639',
    projectId: 'team-socket',
    databaseURL: 'https://team-socket-default-rtdb.firebaseio.com',
    storageBucket: 'team-socket.firebasestorage.app',
    iosBundleId: 'com.example.socket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV6wVv08BaahQeX8eF2Nsyosx9ri_WNlE',
    appId: '1:435112606639:web:db9e820e15af84557c8d5a',
    messagingSenderId: '435112606639',
    projectId: 'team-socket',
    authDomain: 'team-socket.firebaseapp.com',
    databaseURL: 'https://team-socket-default-rtdb.firebaseio.com',
    storageBucket: 'team-socket.firebasestorage.app',
    measurementId: 'G-X9KGLS0SVG',
  );
}
